### ISSUE TITLE
Port the MPU plotting to avionics

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/Propulsion#2]
**Is your feature request related to a problem? Please describe.**
The MPU plotting is in propulsion

**Describe the solution you'd like**
Move the MPU plotting to avionics

**Describe alternatives you've considered**
Not working on it

**Additional context**
NO

**Comment by WashingtonKK** [comment]
Working on it

**Comment by WashingtonKK** [comment]
Done

**Comment by rodneyosodo** [comment]
Can we safely delete [this](https://github.com/nakujaproject/Propulsion/commit/e89b7fa8e772817653303e10289cad334fed17f6)

**Comment by WashingtonKK** [comment]
Yes we can.

**Comment by WashingtonKK** [comment]
😄All the best

**Comment by rodneyosodo** [comment]
Deleted ✅
